create table users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name text not null unique,
  full_name text not null,
  password text not null,
  date_created timestamp not null default now()
);