CREATE TYPE days AS ENUM (
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Daily'
);

 -- gotta to work on if show is everyday...
create table shows (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text not null,
  content text,
  user_id INTEGER references users(id) on delete cascade not null,
  day days not null,
  show_time text not null,
  duration INTEGER not null,
  genre text,
  image text,
  network text,
  uuid text not null
);